"""Download EmoArt from Hugging Face and print its schema.

    python scripts/download_emoart.py              # metadata + images (large)
    python scripts/download_emoart.py --inspect    # only print the schema of what's downloaded

EmoArt is licensed CC BY-NC 4.0 (non-commercial use only). Annotations were
generated by GPT-4o with human verification; 5,600 images were human-validated.
"""
import argparse
from pathlib import Path

import pandas as pd

from artrec.config import EMOART_DIR

REPO_ID = "printblue/EmoArt-130k"
META_EXT = (".parquet", ".jsonl", ".json", ".csv")
NOT_METADATA = {"dimensions.csv"}  # our own size lookup output, written next to the annotations


def find_metadata_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*")
                  if p.suffix.lower() in META_EXT and p.stat().st_size > 0 and p.name not in NOT_METADATA
                  and not any(part.startswith((".", "_")) for part in p.relative_to(root).parts))  # skip .cache/


def read_any(path: Path, nrows: int | None = None) -> pd.DataFrame:
    suf = path.suffix.lower()
    if suf == ".parquet":
        df = pd.read_parquet(path)
        return df.head(nrows) if nrows else df
    if suf == ".csv":
        return pd.read_csv(path, nrows=nrows)
    if suf == ".jsonl":
        return pd.read_json(path, lines=True, nrows=nrows)
    import json
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, dict):  # {id: record} or {"data": [...]}
        data = data.get("data", None) or [dict(v, _key=k) if isinstance(v, dict) else {"_key": k, "value": v}
                                          for k, v in data.items()]
    df = pd.json_normalize(data, sep=".")
    return df.head(nrows) if nrows else df


def inspect(root: Path) -> None:
    files = find_metadata_files(root)
    if not files:
        print(f"No metadata files found under {root}")
        return
    print(f"Found {len(files)} metadata file(s). First few:")
    for f in files[:10]:
        print("  ", f.relative_to(root))
    df = read_any(files[0], nrows=3)
    if any(isinstance(v, dict) for v in df.iloc[0].values):
        df = pd.json_normalize(df.to_dict("records"), sep=".")
    print(f"\nColumns in {files[0].name}:")
    for c in df.columns:
        val = df[c].iloc[0]
        shown = f"<{len(val['bytes'])} image bytes>" if isinstance(val, dict) and "bytes" in val else repr(val)[:100]
        print(f"  {c:40s} {shown}")
    print("\nIf build_catalog.py can't auto-detect a column, pass it with --map field=column")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inspect", action="store_true", help="only inspect already-downloaded files")
    ap.add_argument("--metadata-only", action="store_true", help="skip image archives")
    args = ap.parse_args()
    if not args.inspect:
        from huggingface_hub import snapshot_download
        allow = ["*.parquet", "*.json", "*.jsonl", "*.csv"] if args.metadata_only else None
        # ignore the dataset's README.md: it would overwrite ours in data/emoart/
        snapshot_download(REPO_ID, repo_type="dataset", local_dir=EMOART_DIR, allow_patterns=allow,
                          ignore_patterns=["README.md"])
        print(f"Downloaded to {EMOART_DIR}")
    inspect(EMOART_DIR)


if __name__ == "__main__":
    main()
